/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LokasiProperti;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adam
 */
public class FormLokasi extends javax.swing.JFrame {

    public boolean dataBaru;

    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    Connection con;
    Koneksi db;
    DefaultTableModel model;
    int q, i, id, deleteItem;

    /**
     * Creates new form LokasiProperti
     */
    public FormLokasi() {
        db = new Koneksi();
        initComponents();
        loadData();
    }

    public void loadData() {
        String sql = "SELECT * FROM lokasi";
        try {
            PreparedStatement pst = db.con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tableLokasi.getModel();
            while (rs.next()) {
                model.addRow(new String[]{rs.getString(1), rs.getString(2)});
            }
            model.fireTableDataChanged();
        } catch (Exception ex) {
            System.out.println("Eror" + ex.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableLokasi = new javax.swing.JTable();
        btnTambahLokasi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNamaLokasi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnUpdateLokasi = new javax.swing.JButton();
        btnHapusLokasi = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel1.setText("Daftar Lokasi");

        tableLokasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nama Lokasi"
            }
        ));
        tableLokasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLokasiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableLokasi);

        btnTambahLokasi.setText("Tambah Lokasi");
        btnTambahLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahLokasiActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtNamaLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaLokasiActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Lokasi");

        btnUpdateLokasi.setText("Update Lokasi");
        btnUpdateLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLokasiActionPerformed(evt);
            }
        });

        btnHapusLokasi.setText("Hapus Lokasi");
        btnHapusLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusLokasiActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambahLokasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateLokasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusLokasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnKeluar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahLokasi)
                    .addComponent(btnUpdateLokasi)
                    .addComponent(btnHapusLokasi)
                    .addComponent(btnKeluar))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahLokasiActionPerformed
        try {
            pst = db.con.prepareStatement("insert into lokasi (namaLokasi) VALUES (?)");
            pst.setString(1, txtNamaLokasi.getText());
            pst.executeUpdate();
            loadData();
            JOptionPane.showMessageDialog(null, "Data Lokasi Berhasil Ditambahkan !");
            pst.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnTambahLokasiActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNamaLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaLokasiActionPerformed

    private void btnUpdateLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLokasiActionPerformed
        int row = tableLokasi.getSelectedRow();
            // Mengambil nilai id dari kolom pertama (indeks 0)
            String id = tableLokasi.getValueAt(row, 0).toString();
        try {
            pst = db.con.prepareStatement("UPDATE lokasi SET namaLokasi=? WHERE id=?");
            pst.setString(1, txtNamaLokasi.getText());
            pst.setString(2, id);
            pst.executeUpdate();
            loadData();
            JOptionPane.showMessageDialog(null, "Perubahan Data Lokasi Berhasil Disimpan");
            pst.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateLokasiActionPerformed

    private void btnHapusLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusLokasiActionPerformed
        int row = tableLokasi.getSelectedRow();
        String idHapus = tableLokasi.getValueAt(row, 0).toString();
        String sql = "delete from lokasi where id='"+idHapus+"'";
        
        try {
            st = db.con.createStatement();
            st.execute(sql);
            loadData();
            JOptionPane.showMessageDialog(null, "Data Lokasi Berhasil Dihapus !");
            st.close();   
        } catch (Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }//GEN-LAST:event_btnHapusLokasiActionPerformed
    private JFrame frame;
    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Apakah anda yakin untuk keluar dari program ?", "MYSQL Connector", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION);
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void tableLokasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLokasiMouseClicked
        int row = tableLokasi.getSelectedRow();
        txtId.setText(tableLokasi.getValueAt(row, 1).toString());
        txtNamaLokasi.setText(tableLokasi.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tableLokasiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLokasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLokasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLokasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLokasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLokasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusLokasi;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambahLokasi;
    private javax.swing.JButton btnUpdateLokasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableLokasi;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNamaLokasi;
    // End of variables declaration//GEN-END:variables
}
